### ISSUE TITLE
[Epic] Chat SDK Beta

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/chat-client-js#8]
## Resources

- [Chat Spec](https://github.com/WalletConnect/walletconnect-docs/tree/main/docs/specs/chat)

## Critical Path

This is intended as an overview of critical path work to get to a beta state with the JS Chat SDK, from which we can break out concrete and more detailed individual issues. The list may change and reorder as we see necessary during the development process.

- [x] #9
- [x] #10
- [x] ~Improve client API ergonomics, e.g.~
	- [x] ~Don't require passing of own `address` as method param unless absolutely necessary~
	- [x] ~Don't require passing of `timestamp` for payloads~
- [x] Enhancement: set `chatMessages` for thread X to an empty array immediately when a thread X is created/invite is accepted.
	- [x] This avoids awkward behaviour when querying `chatClient.getMessages`, where the chat thread exists but the `chatMessages` store has no key for it (yet).
